#!/usr/bin/env bash

# Source this file in every ROS 2 terminal that should communicate over
# Tailscale using the Fast DDS discovery server.

export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-23}"
export TAILSCALE_ROS2_DISCOVERY_HOST="${TAILSCALE_ROS2_DISCOVERY_HOST:-100.96.100.117}"
export TAILSCALE_ROS2_DISCOVERY_PORT="${TAILSCALE_ROS2_DISCOVERY_PORT:-11811}"
export ROS_DISCOVERY_SERVER="${ROS_DISCOVERY_SERVER:-${TAILSCALE_ROS2_DISCOVERY_HOST}:${TAILSCALE_ROS2_DISCOVERY_PORT}}"
export ROS_LOCALHOST_ONLY="${ROS_LOCALHOST_ONLY:-0}"
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"

echo "ROS_DOMAIN_ID=${ROS_DOMAIN_ID}"
echo "ROS_DISCOVERY_SERVER=${ROS_DISCOVERY_SERVER}"
echo "ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}"
echo "RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}"
