joint_limits:
  revolute_carriage:
    has_velocity_limits: true
    max_velocity: 1.0472
    has_acceleration_limits: false
  revolute_lift:
    has_velocity_limits: true
    max_velocity: 1.0472
    has_acceleration_limits: false
  revolute_tilt:
    has_velocity_limits: true
    max_velocity: 1.0472
    has_acceleration_limits: false
  revolute_tool:
    has_velocity_limits: true
    max_velocity: 1.0472
    has_acceleration_limits: false
