from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("use_sim_time", default_value="false"),
        DeclareLaunchArgument(" ", default_value="true"),
        DeclareLaunchArgument("use_random_cube", default_value="false"),
        DeclareLaunchArgument("cube_size_m", default_value="0.05"),
        DeclareLaunchArgument("cube_pose_z_offset_m", default_value="0.0"),
        DeclareLaunchArgument("touch_clearance_m", default_value="0.0"),
        DeclareLaunchArgument("cube_command_topic", default_value="/kaivuri/cube_pose_cmd"),
        DeclareLaunchArgument("expert_observation_state_topic", default_value="/kaivuri/expert_observation_state"),
        DeclareLaunchArgument("target_pose_y_topic", default_value="/kaivuri/target_pose_y"),
        DeclareLaunchArgument("max_rot_y_deg_per_step", default_value="5.0"),
        DeclareLaunchArgument("rate_hz", default_value="10.0"),
        DeclareLaunchArgument("speed_mps", default_value="0.04"),
        DeclareLaunchArgument("timeout_s", default_value="180.0"),
        DeclareLaunchArgument("position_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("approach_xy_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("approach_z_tolerance_m", default_value="0.05"),
        DeclareLaunchArgument("touch_xy_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("touch_z_tolerance_m", default_value="0.002"),
        DeclareLaunchArgument("retract_xy_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("retract_z_tolerance_m", default_value="0.05"),
        DeclareLaunchArgument("approach_settle_s", default_value="1.5"),
        DeclareLaunchArgument("hold_s", default_value="1.0"),
        DeclareLaunchArgument("post_touch_record_s", default_value="1.0"),
        DeclareLaunchArgument("record_retract", default_value="true"),
        DeclareLaunchArgument("use_polar_workspace", default_value="true"),
        DeclareLaunchArgument("cube_radius_min", default_value="0.45"),
        DeclareLaunchArgument("cube_radius_max", default_value="0.68"),
        DeclareLaunchArgument("cube_angle_min_deg", default_value="-80.0"),
        DeclareLaunchArgument("cube_angle_max_deg", default_value="80.0"),
        DeclareLaunchArgument("cube_x_min", default_value="0.45"),
        DeclareLaunchArgument("cube_x_max", default_value="0.68"),
        DeclareLaunchArgument("cube_y_min", default_value="-0.15"),
        DeclareLaunchArgument("cube_y_max", default_value="0.15"),
        DeclareLaunchArgument("cube_relocate_delay_s", default_value="1.2"),
        DeclareLaunchArgument("post_episode_cube_ignore_s", default_value="1.0"),
        DeclareLaunchArgument("use_ik_reachability", default_value="false"),
        DeclareLaunchArgument("home_before_episode", default_value="true"),
        DeclareLaunchArgument("default_tool_x", default_value="0.6461694240570068"),
        DeclareLaunchArgument("default_tool_y", default_value="0.0"),
        DeclareLaunchArgument("default_tool_z", default_value="0.09068"),
        DeclareLaunchArgument("home_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("home_settle_s", default_value="2.0"),
        DeclareLaunchArgument("call_recorder_services", default_value="true"),
        DeclareLaunchArgument("recorder_start_service", default_value="/start_episode"),
        DeclareLaunchArgument("recorder_stop_service", default_value="/end_episode"),
        DeclareLaunchArgument("log_target_errors", default_value="false"),
        Node(
            package="kaivuri_bringup",
            executable="cube_touch_expert_node",
            name="cube_touch_expert_node",
            output="screen",
            parameters=[{
                "cube_size_m": LaunchConfiguration("cube_size_m"),
                "use_sim_time": LaunchConfiguration("use_sim_time"),
                "cube_pose_z_offset_m": LaunchConfiguration("cube_pose_z_offset_m"),
                "touch_clearance_m": LaunchConfiguration("touch_clearance_m"),
                "expert_observation_state_topic": LaunchConfiguration("expert_observation_state_topic"),
                "target_pose_y_topic": LaunchConfiguration("target_pose_y_topic"),
                "max_rot_y_deg_per_step": LaunchConfiguration("max_rot_y_deg_per_step"),
                "rate_hz": LaunchConfiguration("rate_hz"),
                "speed_mps": LaunchConfiguration("speed_mps"),
                "timeout_s": LaunchConfiguration("timeout_s"),
                "position_tolerance_m": LaunchConfiguration("position_tolerance_m"),
                "approach_xy_tolerance_m": LaunchConfiguration("approach_xy_tolerance_m"),
                "approach_z_tolerance_m": LaunchConfiguration("approach_z_tolerance_m"),
                "touch_xy_tolerance_m": LaunchConfiguration("touch_xy_tolerance_m"),
                "touch_z_tolerance_m": LaunchConfiguration("touch_z_tolerance_m"),
                "retract_xy_tolerance_m": LaunchConfiguration("retract_xy_tolerance_m"),
                "retract_z_tolerance_m": LaunchConfiguration("retract_z_tolerance_m"),
                "approach_settle_s": LaunchConfiguration("approach_settle_s"),
                "hold_s": LaunchConfiguration("hold_s"),
                "post_touch_record_s": LaunchConfiguration("post_touch_record_s"),
                "record_retract": LaunchConfiguration("record_retract"),
                "post_episode_cube_ignore_s": LaunchConfiguration("post_episode_cube_ignore_s"),
                "home_before_episode": LaunchConfiguration("home_before_episode"),
                "default_tool_x": LaunchConfiguration("default_tool_x"),
                "default_tool_y": LaunchConfiguration("default_tool_y"),
                "default_tool_z": LaunchConfiguration("default_tool_z"),
                "home_tolerance_m": LaunchConfiguration("home_tolerance_m"),
                "home_settle_s": LaunchConfiguration("home_settle_s"),
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
                "call_recorder_services": LaunchConfiguration("call_recorder_services"),
                "recorder_start_service": LaunchConfiguration("recorder_start_service"),
                "recorder_stop_service": LaunchConfiguration("recorder_stop_service"),
                "log_target_errors": LaunchConfiguration("log_target_errors"),
            }],
        ),
        Node(
            package="kaivuri_bringup",
            executable="success_cube_relocator_node",
            name="success_cube_relocator_node",
            output="screen",
            condition=IfCondition(LaunchConfiguration("use_success_cube_relocator")),
            parameters=[{
                "cube_command_topic": LaunchConfiguration("cube_command_topic"),
                "cube_size_m": LaunchConfiguration("cube_size_m"),
                "cube_pose_z_offset_m": LaunchConfiguration("cube_pose_z_offset_m"),
                "touch_clearance_m": LaunchConfiguration("touch_clearance_m"),
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
                "relocate_delay_s": LaunchConfiguration("cube_relocate_delay_s"),
                "use_ik_reachability": LaunchConfiguration("use_ik_reachability"),
            }],
        ),
        Node(
            package="kaivuri_bringup",
            executable="random_cube_pose_node",
            name="random_cube_pose_node",
            output="screen",
            condition=IfCondition(LaunchConfiguration("use_random_cube")),
            parameters=[{
                "period_s": 8.0,
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
            }],
        ),
    ])
