from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("use_success_cube_relocator", default_value="true"),
        DeclareLaunchArgument("use_random_cube", default_value="false"),
        DeclareLaunchArgument("cube_size_m", default_value="0.05"),
        DeclareLaunchArgument("cube_command_topic", default_value="/kaivuri/cube_pose_cmd"),
        DeclareLaunchArgument("rate_hz", default_value="50.0"),
        DeclareLaunchArgument("speed_mps", default_value="0.08"),
        DeclareLaunchArgument("position_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("approach_xy_tolerance_m", default_value="0.005"),
        DeclareLaunchArgument("approach_z_tolerance_m", default_value="0.02"),
        DeclareLaunchArgument("approach_settle_s", default_value="1.5"),
        DeclareLaunchArgument("use_polar_workspace", default_value="true"),
        DeclareLaunchArgument("cube_radius_min", default_value="0.45"),
        DeclareLaunchArgument("cube_radius_max", default_value="0.68"),
        DeclareLaunchArgument("cube_angle_min_deg", default_value="-80.0"),
        DeclareLaunchArgument("cube_angle_max_deg", default_value="80.0"),
        DeclareLaunchArgument("cube_x_min", default_value="0.45"),
        DeclareLaunchArgument("cube_x_max", default_value="0.68"),
        DeclareLaunchArgument("cube_y_min", default_value="-0.15"),
        DeclareLaunchArgument("cube_y_max", default_value="0.15"),
        DeclareLaunchArgument("cube_relocate_delay_s", default_value="1.2"),
        DeclareLaunchArgument("post_episode_cube_ignore_s", default_value="1.0"),
        DeclareLaunchArgument("use_ik_reachability", default_value="true"),
        Node(
            package="kaivuri_bringup",
            executable="cube_touch_expert_node",
            name="cube_touch_expert_node",
            output="screen",
            parameters=[{
                "cube_size_m": LaunchConfiguration("cube_size_m"),
                "rate_hz": LaunchConfiguration("rate_hz"),
                "speed_mps": LaunchConfiguration("speed_mps"),
                "position_tolerance_m": LaunchConfiguration("position_tolerance_m"),
                "approach_xy_tolerance_m": LaunchConfiguration("approach_xy_tolerance_m"),
                "approach_z_tolerance_m": LaunchConfiguration("approach_z_tolerance_m"),
                "approach_settle_s": LaunchConfiguration("approach_settle_s"),
                "post_episode_cube_ignore_s": LaunchConfiguration("post_episode_cube_ignore_s"),
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
            }],
        ),
        Node(
            package="kaivuri_bringup",
            executable="success_cube_relocator_node",
            name="success_cube_relocator_node",
            output="screen",
            condition=IfCondition(LaunchConfiguration("use_success_cube_relocator")),
            parameters=[{
                "cube_command_topic": LaunchConfiguration("cube_command_topic"),
                "cube_size_m": LaunchConfiguration("cube_size_m"),
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
                "relocate_delay_s": LaunchConfiguration("cube_relocate_delay_s"),
                "use_ik_reachability": LaunchConfiguration("use_ik_reachability"),
            }],
        ),
        Node(
            package="kaivuri_bringup",
            executable="random_cube_pose_node",
            name="random_cube_pose_node",
            output="screen",
            condition=IfCondition(LaunchConfiguration("use_random_cube")),
            parameters=[{
                "period_s": 8.0,
                "use_polar_workspace": LaunchConfiguration("use_polar_workspace"),
                "radius_min": LaunchConfiguration("cube_radius_min"),
                "radius_max": LaunchConfiguration("cube_radius_max"),
                "angle_min_deg": LaunchConfiguration("cube_angle_min_deg"),
                "angle_max_deg": LaunchConfiguration("cube_angle_max_deg"),
                "x_min": LaunchConfiguration("cube_x_min"),
                "x_max": LaunchConfiguration("cube_x_max"),
                "y_min": LaunchConfiguration("cube_y_min"),
                "y_max": LaunchConfiguration("cube_y_max"),
            }],
        ),
    ])
